// Create a User Admin
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@admin.com",
    "password": "password",
    "confPassword": "password",
    "role": "admin"
}

###
// Create a User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Test 1",
    "email": "test@test1.com",
    "password": "password",
    "confPassword": "password",
    "role": "user"
}

###
// Get All Users
GET http://localhost:5000/users

###
// Get Single User for token admin
GET http://localhost:5000/users/6439d5dd6617eac67871e388

###
// Get Single User for token user
GET http://localhost:5000/users/7252427b-bb27-4e13-96bd-5fca383054ec

###
// Update User
PATCH http://localhost:5000/users/6439d5dd6617eac67871e388
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@admin.com",
    "password": "password",
    "confPassword": "password",
    "role": "admin"
}

###
// Update User 2
PATCH http://localhost:5000/users/7252427b-bb27-4e13-96bd-5fca383054ec
Content-Type: application/json

{
    "name": "Test edit",
    "email": "test@test1.com",
    "password": "password",
    "confPassword": "password",
    "role": "user"
}

###
// Deleted USER
DELETE http://localhost:5000/users/6439c7426024c41ef230a2b5

###
// Register a User 
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@admin.com",
    "password": "password",
    "confPassword": "password",
    "role": "admin"
}

###
// User Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}

###
// User Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test@test1.com",
    "password": "password"
}

###
// Get detail login User
GET http://localhost:5000/me

###
// User Logout
DELETE  http://localhost:5000/logout

###
// Get All Users
GET http://localhost:5000/products

###
// Get Single Users
GET http://localhost:5000/products/uuid

###
// Create Product  1
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Produk 1",
    "price": 5000
}

###
// Create Product 2
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Produk 2",
    "price": 1000
}

###
// Create Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Produk 2",
    "price": 10000,
}

###
// Update Product
PATCH http://localhost:5000/products/uuid
Content-Type: application/json

{
    "name": "Produk 2 edit",
    "price": 10000,
}

###
// Deleted Product
DELETE http://localhost:5000/products/uuid